$(document).ready(function () {
  $("#calendar").evoCalendar({
    todayHighlight: "true",
    calendarEvents: [
      //  september start
      //-- sept1--//
      {
        id: "sept1",
        name: "American Chess Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Building and Code Staff Appreciation Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Cherry Popover Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Chicken Boy Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Emma M Nutt Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Ginger Cat Appreciation Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "International Cabernet Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Pink Cadillac Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Slovakia Constitution Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Uzbekistan Independence Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Wattle Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "World Letter Writing Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      //-- sept2--//
      {
        id: "sept2",
        name: "Bison-ten Yell Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Bring Your Manners To Work Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Calendar Adjustment Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Ceuta Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "College Colors Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      {
        id: "sept2",
        name: "National Day of Vietnam",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      {
        id: "sept2",
        name: "Pierce Your Ears Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "	Spalding Baseball Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "World Coconut Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "	VJ Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //-- sept2--//
      {
        id: "sept3",
        name: "Foundation Day in San Marin",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "Franchise Appreciation Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "International Bacon Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "Merchant Navy Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      {
        id: "sept3",
        name: "Turkey Vulture Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "US Bowling League Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "World Beard Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept3",
        name: "Yamashita Surrender Day",
        date: "September/3/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept4--//
      {
        id: "sept4",
        name: "Eat an Extra Dessert Day",
        date: "September/4/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept4",
        name: "	National Macadamia Nut Day",
        date: "September/4/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      {
        id: "sept4",
        name: "Umhlanga reed dance Day",
        date: "September/4/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept5--//
      {
        id: "sept5",
        name: "International Day of Charity",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept5",
        name: "Labor Day",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept5",
        name: "Mouthguard Day",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept5",
        name: "World Samosa Day",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept5",
        name: "	West Indian Day Parade",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept5",
        name: "Saint Teresa Canonisation Day in Albania",
        date: "September/5/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept6--//
      {
        id: "sept6",
        name: "	Another Look Unlimited Day",
        date: "September/6/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept6",
        name: "	Bonaire Flag Day",
        date: "September/6/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept6",
        name: "	Fight Procrastination Day",
        date: "September/6/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept6",
        name: "	Janmashtami",
        date: "September/6/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept6",
        name: "Swaziland Independence Day",
        date: "September/6/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept7--//
      {
        id: "sept7",
        name: "Brazil Independence Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "	Buy a Book Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "Fluidra International Pool Pro Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "	Global Talent Acquisition Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "	Google Commemoration Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "International Day of Clean Air",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "	World Duchenne Awareness Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept7",
        name: "	Texas Energy Savings Day",
        date: "September/7/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept8--//
      {
        id: "sept8",
        name: "	Actors' Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept8",
        name: "	Are You Okay Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept8",
        name: "	International Literacy Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept8",
        name: "Pardon Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept8",
        name: "World Literacy Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept8",
        name: "	World Physical Therapy Day",
        date: "September/8/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      //--sept9--//
      {
        id: "sept9",
        name: "International Box Wine Day",
        date: "September/9/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept9",
        name: "International Day to Protect Education from Attack",
        date: "September/9/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept9",
        name: "	International Fetal Alcohol Spectrum Disorders Awareness Day",
        date: "September/9/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept9",
        name: "	International Sudoku Day",
        date: "September/9/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept9",
        name: "Tajikistan Independence Day",
        date: "September/9/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept10--//
      {
        id: "sept10",
        name: "German Language Day",
        date: "September/10/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept10",
        name: "	Gibraltar National Day",
        date: "September/10/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept10",
        name: "Mid-Autumn Festival(China)",
        date: "September/10/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept10",
        name: "World Suicide Prevention Day",
        date: "September/10/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept11--//
      {
        id: "sept11",
        name: "Grandparents Day",
        date: "September/11/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //sept12--//
      {
        id: "sept12",
        name: "United Nations Day for South-South Cooperation",
        date: "September/12/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //sept13--//
      {
        id: "sept13",
        name: "	International Chocolate Day",
        date: "September/13/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept13",
        name: "	Positive Thinking Day",
        date: "September/13/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept13",
        name: "	Programmers Day",
        date: "September/13/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //sept14--//
      {
        id: "sept14",
        name: "	Gobstopper Day",
        date: "September/14/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //sept15--//
      {
        id: "sept15",
        name: "	Costa Rica Independence Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "	El Salvador Independence Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "		Guatemala Independence Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "Honduras Independence Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "	International Day of Democracy",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "International Dot Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "World Afro Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept15",
        name: "	World Engineers Day",
        date: "September/15/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept16--//
      {
        id: "sept16",
        name: "	Barber Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "		International Day for the Preservation of the Ozone Layer",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "		Malaysia Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "	Mayflower Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "	Mexican Independence Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "Papua New Guinea Independence Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept16",
        name: "	World Ozone Day",
        date: "September/16/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept17--//
      {
        id: "sept17",
        name: "	Batman Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "	International Coastal Cleanup Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "	International Country Music Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "		International Eat An Apple Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "		International Grenache Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "International Patient Safety Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept17",
        name: "World Patient Safety Day",
        date: "September/17/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept18--//
      {
        id: "sept18",
        name: "Independence Day(Chile)",
        date: "September/18/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept18",
        name: "International Equal Pay Day",
        date: "September/18/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept18",
        name: "	International Red Panda Day",
        date: "September/18/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept19--//
      {
        id: "sept19",
        name: "	Respect for the Aged Day",
        date: "September/19/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept20--//
      {
        id: "sept20",
        name: "International NFT Day",
        date: "September/20/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept21--//
      {
        id: "sept21",
        name: "Armenia Independence Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "Belize Independence Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "		Escapology Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "International Day of Peace",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "Malta Independence Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "Mid-Autumn Moon Festival(China)",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "World Alzheimer’s Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "World Gratitude Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept21",
        name: "World Mini Golf Day",
        date: "September/21/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept22--//
      {
        id: "sept22",
        name: "	International Day of Radiant Peace",
        date: "September/22/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept22",
        name: "	Mali Independence Day",
        date: "September/22/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept22",
        name: "	World Rhino Day",
        date: "September/22/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept23--//
      {
        id: "sept23",
        name: "American Indian Day",
        date: "September/23/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept23",
        name: "First Day of Autumn",
        date: "September/23/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept23",
        name: "	International Day of Sign Languages",
        date: "September/23/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept24--//
      {
        id: "sept24",
        name: "International Lace Day",
        date: "September/24/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept24",
        name: "	International Rabbit Day",
        date: "September/24/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept24",
        name: "World Bollywood Day",
        date: "September/24/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept25--//
      {
        id: "sept25",
        name: "World Day of The Deaf",
        date: "September/25/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept25",
        name: "World Dream Day",
        date: "September/25/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept25",
        name: "World Pharmacists Day",
        date: "September/25/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept25",
        name: "	World Rivers Day",
        date: "September/25/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept26--//
      {
        id: "sept26",
        name: "European Languages Day",
        date: "September/26/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept26",
        name: "	International Day for the Total Elimination of Nuclear Weapons",
        date: "September/26/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept26",
        name: "	Love Note Day",
        date: "September/26/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept26",
        name: "	Navratri",
        date: "September/26/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept27--//
      {
        id: "sept27",
        name: "World Tourism Day",
        date: "September/27/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept28--//
      {
        id: "sept28",
        name: "	International Day for Universal Access to Information",
        date: "September/28/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept28",
        name: "	International Poke Day",
        date: "September/28/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept28",
        name: "	International Right To Know Day",
        date: "September/28/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept28",
        name: "	World Rabies Day",
        date: "September/28/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept29--//
      {
        id: "sept29",
        name: "International Day of Awareness of Food Loss and Waste",
        date: "September/29/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept29",
        name: "	International Happy Goose Day",
        date: "September/29/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept29",
        name: "	World Heart Day",
        date: "September/29/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept29",
        name: "	World Maritime Day",
        date: "September/29/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      //--sept30--//
      {
        id: "sept30",
        name: "	International Blasphemy Rights Day",
        date: "September/30/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept30",
        name: "	International Podcast Day",
        date: "September/30/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept30",
        name: "		International Translation Day",
        date: "September/30/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept30",
        name: "		International Translation Day",
        date: "September/30/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept30",
        name: "Orange Shirt Day",
        date: "September/30/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      // september exit
    ],
  });
});
