$(document).ready(function () {
  $("#calendar").evoCalendar({
    todayHighlight: "true",
    calendarEvents: [
      //  september start
      //-- sept1--//
      {
        id: "sept1",
        name: "American Chess Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Building and Code Staff Appreciation Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Cherry Popover Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Chicken Boy Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Emma M Nutt Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Ginger Cat Appreciation Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "International Cabernet Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "National Acne Positivity Day(US)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "	National Child Identity Theft Awareness Day(US)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "	National Little Black Dress Day(US)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "	National Monterey County Fair Day(US)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "	National No Rhyme Nor Reason Day(US)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "National Tofu Day(UK)",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Pink Cadillac Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Slovakia Constitution Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Uzbekistan Independence Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "Wattle Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept1",
        name: "World Letter Writing Day",
        date: "September/1/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },

      //-- sept2--//
      {
        id: "sept2",
        name: "Bison-ten Yell Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Bring Your Manners To Work Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Calendar Adjustment Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Ceuta Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "College Colors Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "	National Blueberry Popsicle Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "National Chianti Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "National Day of Vietnam",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "National Food Bank Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "National Lazy Mom’s Day(US & Other)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "National Live Fearless Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "Pierce Your Ears Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "	Spalding Baseball Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "World Coconut Day",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      {
        id: "sept2",
        name: "	VJ Day(US)",
        date: "September/2/2022",
        type: "event",
        everyYear: true,
        color: "#004EFF",
      },
      // september exit
    ],
  });
});
